# Generated by Django 6.0.5 on 2026-07-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_daily_briefing_pref'),
        ('organizations', '0002_organization_surface_color'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='notificatio_user_id_1159a5_idx',
            old_name='notif_pushsub_user_act_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('meeting_invited', 'Invitation réunion'), ('meeting_reminder', 'Rappel réunion'), ('meeting_started', 'Réunion démarrée'), ('meeting_completed', 'Réunion clôturée'), ('agenda_validated', 'Ordre du jour validé'), ('decision_assigned', 'Décision assignée'), ('decision_approved', 'Décision validée'), ('decision_deadline', 'Échéance décision'), ('decision_action_delay', "Décision en retard d'exécution"), ('task_assigned', 'Tâche assignée'), ('task_delegated', 'Tâche déléguée'), ('task_reminder', 'Rappel tâche'), ('task_deadline', 'Échéance tâche'), ('task_due_soon', 'Échéance proche'), ('task_overdue', 'Tâche en retard'), ('manager_daily_summary', 'Résumé manager'), ('action_plan_blocked', "Plan d'action bloqué"), ('action_plan_completed', "Plan d'action clôturé"), ('plan_completed', "Plan d'action clôturé (legacy)"), ('user_created', 'Bienvenue — compte créé'), ('user_password_reset', 'Mot de passe réinitialisé'), ('user_reassigned', 'Affectation mise à jour'), ('user_deactivated', 'Compte désactivé'), ('user_reactivated', 'Compte réactivé'), ('weekly_user_digest', 'Synthèse hebdomadaire des tâches'), ('daily_briefing', 'Briefing matinal quotidien')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='proactive_agent_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pushsubscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
    ]
