# Generated by Django 6.0.5 on 2026-07-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0004_semanticindex'),
        ('organizations', '0002_organization_surface_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semanticindex',
            options={},
        ),
        migrations.RenameIndex(
            model_name='aiactionrequest',
            new_name='ai_engine_a_convers_fed25f_idx',
            old_name='ai_engine_a_convers_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='aiactionrequest',
            new_name='ai_engine_a_request_f61094_idx',
            old_name='ai_engine_a_user_stat_idx',
        ),
        migrations.RenameIndex(
            model_name='aidocumentembedding',
            new_name='ai_engine_a_organiz_7fbd9e_idx',
            old_name='ai_engine_a_organiz_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='aidocumentembedding',
            new_name='ai_engine_a_organiz_eeb91e_idx',
            old_name='ai_engine_a_organiz_lang_idx',
        ),
        migrations.RenameIndex(
            model_name='aiinferencelog',
            new_name='ai_engine_a_organiz_e06307_idx',
            old_name='ai_engine_a_organiz_2af3c1_idx',
        ),
        migrations.RenameIndex(
            model_name='aiinferencelog',
            new_name='ai_engine_a_capabil_4f0630_idx',
            old_name='ai_engine_a_capabil_5d31a7_idx',
        ),
        migrations.RenameIndex(
            model_name='proactivealert',
            new_name='ai_engine_p_user_id_3d337c_idx',
            old_name='ai_engine_p_user_id_idx_pa',
        ),
        migrations.RenameIndex(
            model_name='proactivealert',
            new_name='ai_engine_p_organiz_1630ff_idx',
            old_name='ai_engine_p_org_idx_pa',
        ),
        migrations.RenameIndex(
            model_name='semanticindex',
            new_name='ai_engine_s_organiz_fa2de4_idx',
            old_name='ai_eng_si_org_type_idx',
        ),
        migrations.RenameIndex(
            model_name='semanticindex',
            new_name='ai_engine_s_organiz_912b3e_idx',
            old_name='ai_eng_si_org_mver_idx',
        ),
        migrations.AlterField(
            model_name='aiinferencelog',
            name='risk_class',
            field=models.CharField(default='low', help_text='AI Act classification', max_length=20),
        ),
        migrations.AlterField(
            model_name='aimessage',
            name='feedback',
            field=models.SmallIntegerField(blank=True, help_text='+1 / -1 user feedback', null=True),
        ),
        migrations.AlterField(
            model_name='proactivealert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='proactivealert',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='semanticindex',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='semanticindex',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
    ]
