# Generated by Django 6.0.5 on 2026-07-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_membership_subsidiary'),
        ('organizations', '0002_organization_surface_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='subsidiary',
            field=models.ForeignKey(blank=True, help_text='Filiale principale du collaborateur (null pour les rôles transverses Groupe).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='organizations.subsidiary'),
        ),
    ]
