# Generated by Django 6.0.5 on 2026-05-13 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_validated', models.BooleanField(db_index=True, default=False)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('notes_md', models.TextField(blank=True)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='meetings.meeting')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas_validated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('title', models.CharField(max_length=300)),
                ('description_md', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=10)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=15)),
                ('actual_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'À traiter'), ('in_progress', 'En cours'), ('discussed', 'Traité'), ('postponed', 'Reporté'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('discussion_notes_md', models.TextField(blank=True, help_text='Synthèse de la discussion')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agendas.agenda')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['agenda_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AgendaItemComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_md', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='agendas.agendaitem')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agenda',
            index=models.Index(fields=['organization', '-created_at'], name='agendas_age_organiz_0ff9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaitem',
            index=models.Index(fields=['agenda', 'order'], name='agendas_age_agenda__8db29c_idx'),
        ),
        migrations.AddIndex(
            model_name='agendaitem',
            index=models.Index(fields=['organization', 'status'], name='agendas_age_organiz_e19033_idx'),
        ),
    ]
