# Generated by Django 6.0.5 on 2026-07-15 10:50

import apps.meeting_recordings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_recordings', '0003_voice_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='detectedspeaker',
            new_name='meeting_rec_recordi_be7e94_idx',
            old_name='mr_dspk_rec_conf_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingrecording',
            new_name='meeting_rec_organiz_354df6_idx',
            old_name='mr_rec_org_meet_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingrecording',
            new_name='meeting_rec_organiz_15feaa_idx',
            old_name='mr_rec_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingrecording',
            new_name='meeting_rec_organiz_8cf836_idx',
            old_name='mr_rec_org_user_idx',
        ),
        migrations.RenameIndex(
            model_name='recordingaiextraction',
            new_name='meeting_rec_recordi_7131ed_idx',
            old_name='mr_extr_rec_type_idx',
        ),
        migrations.RenameIndex(
            model_name='recordingaiextraction',
            new_name='meeting_rec_organiz_47b2a5_idx',
            old_name='mr_extr_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='recordingchunk',
            new_name='meeting_rec_recordi_c1d69b_idx',
            old_name='mr_chk_rec_idx',
        ),
        migrations.RenameIndex(
            model_name='speakerparticipantmapping',
            new_name='meeting_rec_recordi_e92d43_idx',
            old_name='mr_map_rec_spk_idx',
        ),
        migrations.RenameIndex(
            model_name='speakerparticipantmapping',
            new_name='meeting_rec_partici_6183c9_idx',
            old_name='mr_map_part_idx',
        ),
        migrations.RenameIndex(
            model_name='speakersegment',
            new_name='meeting_rec_recordi_29505e_idx',
            old_name='mr_seg_rec_start_idx',
        ),
        migrations.RenameIndex(
            model_name='speakersegment',
            new_name='meeting_rec_recordi_2d84b1_idx',
            old_name='mr_seg_rec_spk_idx',
        ),
        migrations.RenameIndex(
            model_name='voiceprofile',
            new_name='meeting_rec_organiz_523428_idx',
            old_name='voice_profil_organiz_8e6cb6_idx',
        ),
        migrations.RenameIndex(
            model_name='voiceprofilesample',
            new_name='meeting_rec_voice_p_0f3363_idx',
            old_name='voice_profil_voice_p_a2c1f4_idx',
        ),
        migrations.AlterField(
            model_name='detectedspeaker',
            name='display_name',
            field=models.CharField(blank=True, help_text="Nom affiché dans l'UI (au final = nom réel mappé).", max_length=200),
        ),
        migrations.AlterField(
            model_name='detectedspeaker',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text="True quand l'utilisateur a explicitement validé l'association."),
        ),
        migrations.AlterField(
            model_name='detectedspeaker',
            name='sample_audio',
            field=models.FileField(blank=True, help_text="Extrait audio représentatif pour écoute par l'utilisateur.", max_length=600, null=True, storage=apps.meeting_recordings.models._recordings_storage, upload_to=apps.meeting_recordings.models._speaker_sample_upload_path),
        ),
        migrations.AlterField(
            model_name='detectedspeaker',
            name='total_duration',
            field=models.FloatField(default=0, help_text='Secondes parlées au total.'),
        ),
        migrations.AlterField(
            model_name='detectedspeaker',
            name='voice_match_confidence',
            field=models.FloatField(default=0.0, help_text='Score de matching avec un VoiceProfile existant (0..1). 0 = pas de match au-dessus du seuil. > 0.75 = match confiant. Renseigné automatiquement après diarisation si Resemblyzer dispo.'),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='ai_minutes',
            field=models.TextField(blank=True, help_text='Compte rendu structuré Markdown (peut alimenter Meeting.final_notes_md).'),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='audio_file',
            field=models.FileField(blank=True, help_text="Fichier audio source (webm/ogg/wav/mp3). Vide tant qu'aucun upload.", max_length=600, null=True, storage=apps.meeting_recordings.models._recordings_storage, upload_to=apps.meeting_recordings.models._audio_upload_path),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='audio_normalized',
            field=models.FileField(blank=True, help_text='Version normalisée wav 16kHz mono (utilisée pour samples speakers).', max_length=600, null=True, storage=apps.meeting_recordings.models._recordings_storage, upload_to=apps.meeting_recordings.models._audio_upload_path),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='consent_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text="Quand l'utilisateur a confirmé l'information des participants.", null=True),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='deleted_audio_at',
            field=models.DateTimeField(blank=True, help_text="Si renseigné : l'audio brut a été purgé (rétention).", null=True),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='Octets'),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a déclenché la capture (secrétaire/chair en général).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordings_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='summary',
            field=models.TextField(blank=True, help_text='Résumé exécutif Markdown.'),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='transcript_final',
            field=models.JSONField(blank=True, default=list, help_text='Même format, mais avec speaker remplacé par display_name réel.'),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='transcript_raw',
            field=models.TextField(blank=True, help_text='Sortie brute de transcription, sans speaker labels.'),
        ),
        migrations.AlterField(
            model_name='meetingrecording',
            name='transcript_with_speakers',
            field=models.JSONField(blank=True, default=list, help_text='Liste de segments [{speaker, start, end, text}, ...] avant mapping.'),
        ),
        migrations.AlterField(
            model_name='recordingchunk',
            name='checksum',
            field=models.CharField(blank=True, help_text='sha256 hex.', max_length=64),
        ),
        migrations.AlterField(
            model_name='recordingchunk',
            name='end_time',
            field=models.FloatField(default=0, help_text='Offset fin (sec).'),
        ),
        migrations.AlterField(
            model_name='recordingchunk',
            name='index',
            field=models.PositiveIntegerField(help_text='Ordre du chunk (0-based).'),
        ),
        migrations.AlterField(
            model_name='recordingchunk',
            name='start_time',
            field=models.FloatField(default=0, help_text='Offset début (sec).'),
        ),
        migrations.AlterField(
            model_name='speakerparticipantmapping',
            name='confidence',
            field=models.FloatField(default=1.0, help_text='1.0 si confirmé manuellement.'),
        ),
        migrations.AlterField(
            model_name='speakersegment',
            name='audio_excerpt',
            field=models.FileField(blank=True, max_length=600, null=True, storage=apps.meeting_recordings.models._recordings_storage, upload_to=apps.meeting_recordings.models._speaker_sample_upload_path),
        ),
        migrations.AlterField(
            model_name='speakersegment',
            name='confidence',
            field=models.FloatField(default=0, help_text='Score confiance ASR (0..1) si fourni par le provider.'),
        ),
        migrations.AlterField(
            model_name='speakersegment',
            name='end_time',
            field=models.FloatField(help_text='Offset fin (sec).'),
        ),
        migrations.AlterField(
            model_name='speakersegment',
            name='speaker_label',
            field=models.CharField(db_index=True, help_text='SPEAKER_00 / SPEAKER_01 / ... (avant mapping manuel).', max_length=40),
        ),
        migrations.AlterField(
            model_name='speakersegment',
            name='start_time',
            field=models.FloatField(help_text="Offset début dans l'audio (sec)."),
        ),
        migrations.AlterField(
            model_name='voiceprofile',
            name='embedding',
            field=models.JSONField(blank=True, default=list, help_text='Vecteur moyen 256-dim (Resemblyzer). Vide si pas encore appris.'),
        ),
        migrations.AlterField(
            model_name='voiceprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False pour désactiver le matching auto sur ce user (RGPD opt-out).'),
        ),
        migrations.AlterField(
            model_name='voiceprofile',
            name='sample_count',
            field=models.PositiveIntegerField(default=0, help_text="Nombre d'extraits cumulés pour calculer l'embedding moyen."),
        ),
        migrations.AlterField(
            model_name='voiceprofilesample',
            name='added_by',
            field=models.ForeignKey(blank=True, help_text="Qui a validé le mapping qui a permis d'apprendre cette voix.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voice_samples_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voiceprofilesample',
            name='quality_score',
            field=models.FloatField(default=1.0, help_text='Estimation qualité (durée + SNR). Pondère la moyenne.'),
        ),
    ]
