# Generated by Django 6.0.5 on 2026-05-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_smart_notes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meetingnote',
            name='meetings_me_organiz_0710f6_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingdetectedaction',
            new_name='meetings_me_meeting_473d61_idx',
            old_name='mtg_da_status_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingdetectedaction',
            new_name='meetings_me_detecte_3e60fa_idx',
            old_name='mtg_da_dd_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingdetecteddecision',
            new_name='meetings_me_meeting_803950_idx',
            old_name='mtg_dd_status_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingmention',
            new_name='meetings_me_meeting_0662a8_idx',
            old_name='mtg_mention_user_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingnote',
            new_name='meetings_me_meeting_9088bf_idx',
            old_name='mtg_note_curr_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingnote',
            new_name='meetings_me_meeting_e29b7f_idx',
            old_name='mtg_note_ver_idx',
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='content_json',
            field=models.JSONField(blank=True, default=dict, help_text='Document ProseMirror (Tiptap).'),
        ),
    ]
