# Generated by Django 6.0.5 on 2026-05-13 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('target_persona', models.CharField(choices=[('dg', 'DG'), ('daf', 'DAF'), ('drh', 'DRH'), ('dsi', 'DSI'), ('dt', 'Directeur Technique'), ('dc', 'Directeur Commercial'), ('pmo', 'PMO'), ('audit', 'Audit'), ('custom', 'Personnalisé')], default='custom', max_length=20)),
                ('is_template', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('layout_json', models.JSONField(blank=True, default=list, help_text='gridstack layout')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget_type', models.CharField(choices=[('kpi_card', 'KPI Card'), ('line_chart', 'Line Chart'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('heatmap', 'Heatmap'), ('radar', 'Radar'), ('table', 'Tableau'), ('text', 'Texte / Markdown'), ('feed', "Feed d'activité"), ('ai_briefing', 'Briefing IA'), ('powerbi_embed', 'Power BI Embed')], max_length=30)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('data_source', models.JSONField(blank=True, default=dict)),
                ('format', models.JSONField(blank=True, default=dict)),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('position', models.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField(default=0)),
                ('refresh_interval_seconds', models.PositiveIntegerField(default=60)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboards.dashboard')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'ordering': ['dashboard', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['organization', 'owner'], name='dashboards__organiz_8dd041_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['organization', 'is_template'], name='dashboards__organiz_4efdf1_idx'),
        ),
    ]
