# Generated by Django 6.0.5 on 2026-07-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_episcoresnapshot'),
        ('organizations', '0002_organization_surface_color'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='episcoresnapshot',
            new_name='dashboards__organiz_a9aaea_idx',
            old_name='dashboards__org_dat_idx',
        ),
        migrations.AlterField(
            model_name='episcoresnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization'),
        ),
    ]
