# Generated by Django 6.0.5 on 2026-05-13 23:36

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('legal_form', models.CharField(blank=True, max_length=80)),
                ('siret', models.CharField(blank=True, max_length=20)),
                ('vat_number', models.CharField(blank=True, max_length=40)),
                ('logo', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#2563eb', max_length=7)),
                ('secondary_color', models.CharField(default='#0ea5e9', max_length=7)),
                ('country', models.CharField(default='FR', max_length=2)),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('plan', models.CharField(choices=[('essential', 'Essential'), ('enterprise', 'Enterprise'), ('sovereign', 'Sovereign')], default='essential', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sso_enforced', models.BooleanField(default=False)),
                ('sso_provider', models.CharField(blank=True, max_length=40)),
                ('data_residency', models.CharField(default='eu-west', max_length=20)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_048085_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_1ffc28_idx')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subsidiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('legal_form', models.CharField(blank=True, max_length=80)),
                ('siret', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(max_length=2)),
                ('currency', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsidiaries', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.subsidiary')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'name'], name='organizatio_organiz_c384ac_idx')],
            },
            managers=[
                ('unscoped', django.db.models.manager.Manager()),
            ],
        ),
    ]
