# Generated by Django 6.0.5 on 2026-05-13 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('meeting_type', models.CharField(choices=[('regular', 'Ordinaire'), ('extraordinary', 'Extraordinaire'), ('strategic', 'Stratégique'), ('crisis', 'De crise')], default='regular', max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Lieu physique', max_length=300)),
                ('video_url', models.URLField(blank=True, help_text='Lien Teams / Zoom / Meet')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('scheduled', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=20)),
                ('quorum_min', models.PositiveIntegerField(default=0, help_text='Quorum requis (0 = pas de contrôle)')),
                ('quorum_reached', models.BooleanField(default=False)),
                ('final_notes_md', models.TextField(blank=True, help_text='Notes finales du secrétaire')),
                ('minutes_generated_at', models.DateTimeField(blank=True, null=True)),
                ('chair', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chaired_meetings', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_created', to=settings.AUTH_USER_MODEL)),
                ('minutes_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings_as_minutes', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kept_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinutes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=250)),
                ('body_html', models.TextField()),
                ('body_md', models.TextField(blank=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting_minutes_doc', to='documents.document')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minutes_generated', to=settings.AUTH_USER_MODEL)),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='meetings.meeting')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_md', models.TextField()),
                ('is_private', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='meetings.meeting')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_email', models.EmailField(blank=True, help_text='Si invité externe', max_length=254, null=True)),
                ('external_name', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('chair', 'Président'), ('secretary', 'Secrétaire'), ('member', 'Membre'), ('invited', 'Invité'), ('observer', 'Observateur')], default='member', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='meetings.meeting')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Invité'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('present', 'Présent'), ('absent', 'Absent'), ('late', 'En retard')], default='invited', max_length=20)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='meetings.meeting')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_recorded', to=settings.AUTH_USER_MODEL)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='meetings.meetingparticipant')),
            ],
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organization', 'scheduled_start'], name='meetings_me_organiz_1c388c_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['organization', 'status'], name='meetings_me_organiz_5cee97_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['chair'], name='meetings_me_chair_i_04667d_idx'),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['secretary'], name='meetings_me_secreta_72c4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingminutes',
            index=models.Index(fields=['organization', '-created_at'], name='meetings_me_organiz_ff450d_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingnote',
            index=models.Index(fields=['organization', '-created_at'], name='meetings_me_organiz_0710f6_idx'),
        ),
        migrations.AddIndex(
            model_name='meetingparticipant',
            index=models.Index(fields=['meeting', 'role'], name='meetings_me_meeting_0043b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('meeting', 'user'), name='uniq_meeting_participant_user'),
        ),
        migrations.AddConstraint(
            model_name='meetingparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('external_email__isnull', False)), fields=('meeting', 'external_email'), name='uniq_meeting_participant_external_email'),
        ),
        migrations.AddIndex(
            model_name='meetingattendance',
            index=models.Index(fields=['meeting', 'status'], name='meetings_me_meeting_25bf27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='meetingattendance',
            unique_together={('meeting', 'participant')},
        ),
    ]
