# Generated by Django 6.0.5 on 2026-07-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_detected_action_metadata'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meetingnote',
            name='meetings_me_organiz_0710f6_idx',
        ),
        migrations.RenameIndex(
            model_name='meeting',
            new_name='meetings_me_series__651ebb_idx',
            old_name='meetings_me_series_dt_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingdetectedaction',
            new_name='meetings_me_meeting_473d61_idx',
            old_name='mtg_da_status_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingdetectedaction',
            new_name='meetings_me_detecte_3e60fa_idx',
            old_name='mtg_da_dd_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingdetecteddecision',
            new_name='meetings_me_meeting_803950_idx',
            old_name='mtg_dd_status_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingmention',
            new_name='meetings_me_meeting_0662a8_idx',
            old_name='mtg_mention_user_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingnote',
            new_name='meetings_me_meeting_9088bf_idx',
            old_name='mtg_note_curr_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingnote',
            new_name='meetings_me_meeting_e29b7f_idx',
            old_name='mtg_note_ver_idx',
        ),
        migrations.RenameIndex(
            model_name='meetingseries',
            new_name='meetings_me_organiz_c40efd_idx',
            old_name='meetings_se_org_act_idx',
        ),
        migrations.AlterField(
            model_name='meetingnote',
            name='content_json',
            field=models.JSONField(blank=True, default=dict, help_text='Document ProseMirror (Tiptap).'),
        ),
        migrations.AlterField(
            model_name='meetingseries',
            name='last_generated_until',
            field=models.DateField(blank=True, help_text="Date jusqu'à laquelle les instances ont été générées.", null=True),
        ),
        migrations.AlterField(
            model_name='meetingseries',
            name='starts_on',
            field=models.DateField(blank=True, help_text="Date à partir de laquelle la série démarre (default : aujourd'hui).", null=True),
        ),
    ]
