# Generated by Django 6.0.5 on 2026-05-13 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('meeting_invited', 'Invitation réunion'), ('meeting_reminder', 'Rappel réunion'), ('meeting_started', 'Réunion démarrée'), ('meeting_completed', 'Réunion clôturée'), ('agenda_validated', 'Ordre du jour validé'), ('decision_assigned', 'Décision assignée'), ('decision_approved', 'Décision validée'), ('decision_deadline', 'Échéance décision'), ('task_assigned', 'Tâche assignée'), ('task_deadline', 'Échéance tâche'), ('task_overdue', 'Tâche en retard'), ('plan_completed', "Plan d'action clôturé")], db_index=True, max_length=40)),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Critique')], default='info', max_length=10)),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, max_length=500)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'seen_at'], name='notificatio_recipie_2deb54_idx'), models.Index(fields=['organization', 'event'], name='notificatio_organiz_f9d422_idx')],
            },
        ),
    ]
