# Generated by Django 6.0.5 on 2026-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_preferences_logs_reminderlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_a9e57f_idx',
            old_name='notif_recip_chan_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_subsidi_e5f30f_idx',
            old_name='notif_sub_event_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_notific_d8c030_idx',
            old_name='notif_log_notif_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationlog',
            new_name='notificatio_channel_e01687_idx',
            old_name='notif_log_chan_idx',
        ),
        migrations.RenameIndex(
            model_name='notificationpreference',
            new_name='notificatio_user_id_0299fd_idx',
            old_name='notif_pref_user_idx',
        ),
        migrations.RenameIndex(
            model_name='taskreminderlog',
            new_name='notificatio_user_id_7228d1_idx',
            old_name='task_rem_user_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text="Lien profond frontend pour rebondir sur l'objet métier.", max_length=500),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='provider',
            field=models.CharField(help_text='smtp.hostinger / twilio / fcm / …', max_length=40),
        ),
    ]
