# Generated by Django 6.0.5 on 2026-05-13 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decisions', '0001_initial'),
        ('documents', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description_md', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('blocked', 'Bloqué'), ('cancelled', 'Annulé')], db_index=True, default='open', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan', to='decisions.decision')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_plans_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description_md', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('done', 'Fait'), ('blocked', 'Bloqué'), ('overdue', 'En retard'), ('cancelled', 'Annulé')], db_index=True, default='todo', max_length=20)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0)),
                ('effort_estimate_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('effort_actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('action_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='action_plans.actionplan')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='action_plans.actiontask')),
            ],
            options={
                'ordering': ['action_plan', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_evidence', to='documents.document')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_submitted', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='action_plans.actiontask')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActionComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_md', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('action_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='action_plans.actionplan')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='action_plans.actiontask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='actionplan',
            index=models.Index(fields=['organization', 'status'], name='action_plan_organiz_7fee9c_idx'),
        ),
        migrations.AddIndex(
            model_name='actiontask',
            index=models.Index(fields=['action_plan', 'status'], name='action_plan_action__e92365_idx'),
        ),
        migrations.AddIndex(
            model_name='actiontask',
            index=models.Index(fields=['assignee', 'due_date'], name='action_plan_assigne_7b251a_idx'),
        ),
        migrations.AddIndex(
            model_name='actiontask',
            index=models.Index(fields=['organization', 'status', 'due_date'], name='action_plan_organiz_caf491_idx'),
        ),
        migrations.AddIndex(
            model_name='actionevidence',
            index=models.Index(fields=['organization', '-created_at'], name='action_plan_organiz_8640b9_idx'),
        ),
        migrations.AddIndex(
            model_name='actioncomment',
            index=models.Index(fields=['task', 'created_at'], name='action_plan_task_id_f1ebcf_idx'),
        ),
    ]
