# Generated by Django 6.0.5 on 2026-05-13 23:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('created', 'Créé'), ('updated', 'Mis à jour'), ('deleted', 'Supprimé'), ('validated', 'Validé'), ('approved', 'Approuvé'), ('closed', 'Clôturé'), ('started', 'Démarré'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('custom', 'Custom')], db_index=True, max_length=30)),
                ('target_id', models.CharField(blank=True, max_length=80)),
                ('target_repr', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=400)),
                ('diff_json', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_logs__organiz_adc99e_idx'), models.Index(fields=['target_type', 'target_id', '-created_at'], name='audit_logs__target__52c628_idx'), models.Index(fields=['actor', '-created_at'], name='audit_logs__actor_i_bca6af_idx')],
            },
        ),
    ]
